version: '2'

services:
  db:
    image: ${MYSQL_IMAGE}:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}_db
    env_file: .env
    volumes:
      - ./${MYSQL_SEED}:/docker-entrypoint-initdb.d/seed.sql

  php-fpm:
    image: ${PHP_FPM_IMAGE}:${PHP_FPM_VERSION}
    container_name: ${PROJECT_NAME}_php
    env_file: .env
    volumes:
      - ./${PHP_FPM_CONFIGURATION}:/usr/local/etc/php-fpm.d/www.conf
      - ./${SOURCE_FOLDER}:/var/www/html
      - xdebug:/tmp/xdebug

  nginx:
    image: ${NGINX_IMAGE}:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${LOCAL_HTTP_PORT}:80
      - ${LOCAL_HTTPS_PORT}:443
    volumes:
      - ./${NGINX_CONFIGURATION}:/etc/nginx/conf.d/default.conf
      - ./${SOURCE_FOLDER}:/var/www/html

  webgrind:
    image: ${WEBGRIND_IMAGE}
    container_name: ${PROJECT_NAME}_webgrind
    ports:
      - ${WEBGRIND_HTTP_PORT}:80
    volumes:
      - xdebug:/tmp/xdebug

volumes:
  xdebug:
