version: '2'

services:
  db:
    image: mysql/mysql-server:${MYSQL_VERSION}
    container_name: ${PROJECT_NAME}_db
    env_file: .env
    volumes:
      - ./${MYSQL_SEED}:/docker-entrypoint-initdb.d/seed.sql

  php-fpm:
    image: creativeprojects/php-fpm:${PHP_FPM_VERSION}
    container_name: ${PROJECT_NAME}_php
    env_file: .env
    volumes:
      - ./${PHP_FPM_CONFIGURATION}:/usr/local/etc/php-fpm.d/www.conf
      - ./${SOURCE_FOLDER}:/var/www/html

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${LOCAL_HTTP_PORT}:80
      - ${LOCAL_HTTPS_PORT}:443
    volumes:
      - ./${NGINX_CONFIGURATION}:/etc/nginx/conf.d/default.conf
      - ./${SOURCE_FOLDER}:/var/www/html
