version: '2'

services:
  db:
    image: mysql/mysql-server:5.5
    container_name: ${PROJECT_NAME}_db
    env_file: .env
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql

  php-fpm:
    image: creativeprojects/php-fpm:latest
    container_name: ${PROJECT_NAME}_php
    env_file: .env
    volumes:
      - ./php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./src:/var/www/html

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - ${LOCAL_HTTP_PORT}:80
      - ${LOCAL_HTTPS_PORT}:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
